addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

services: docker

env:
  matrix:
  - INSTANCE=lwrp-chain-create-default-ubuntu-1604
  - INSTANCE=lwrp-chain-create-default-ubuntu-1804
  - INSTANCE=lwrp-chain-create-default-ubuntu-1904
  - INSTANCE=lwrp-chain-create-default-debian-8
  - INSTANCE=lwrp-chain-create-default-debian-9
  - INSTANCE=lwrp-chain-create-default-debian-10
  - INSTANCE=lwrp-chain-create-default-centos-6
  - INSTANCE=lwrp-chain-create-default-centos-7
  - INSTANCE=lwrp-chain-create-custom-ubuntu-1604
  - INSTANCE=lwrp-chain-create-custom-ubuntu-1804
  - INSTANCE=lwrp-chain-create-custom-ubuntu-1904
  - INSTANCE=lwrp-chain-create-custom-debian-8
  - INSTANCE=lwrp-chain-create-custom-debian-9
  - INSTANCE=lwrp-chain-create-custom-debian-10
  - INSTANCE=lwrp-chain-create-custom-centos-6
  - INSTANCE=lwrp-chain-create-custom-centos-7
  - INSTANCE=lwrp-chain-create-if-missing-ubuntu-1604
  - INSTANCE=lwrp-chain-create-if-missing-ubuntu-1804
  - INSTANCE=lwrp-chain-create-if-missing-ubuntu-1904
  - INSTANCE=lwrp-chain-create-if-missing-debian-8
  - INSTANCE=lwrp-chain-create-if-missing-debian-9
  - INSTANCE=lwrp-chain-create-if-missing-debian-10
  - INSTANCE=lwrp-chain-create-if-missing-centos-6
  - INSTANCE=lwrp-chain-create-if-missing-centos-7
  - INSTANCE=lwrp-chain-create-empty-ubuntu-1604
  - INSTANCE=lwrp-chain-create-empty-ubuntu-1804
  - INSTANCE=lwrp-chain-create-empty-ubuntu-1904
  - INSTANCE=lwrp-chain-create-empty-debian-8
  - INSTANCE=lwrp-chain-create-empty-debian-9
  - INSTANCE=lwrp-chain-create-empty-debian-10
  - INSTANCE=lwrp-chain-create-empty-centos-6
  - INSTANCE=lwrp-chain-create-empty-centos-7
  - INSTANCE=lwrp-rule-create-default-ubuntu-1604
  - INSTANCE=lwrp-rule-create-default-ubuntu-1804
  - INSTANCE=lwrp-rule-create-default-ubuntu-1904
  - INSTANCE=lwrp-rule-create-default-debian-8
  - INSTANCE=lwrp-rule-create-default-debian-9
  - INSTANCE=lwrp-rule-create-default-debian-10
  - INSTANCE=lwrp-rule-create-default-centos-6
  - INSTANCE=lwrp-rule-create-default-centos-7
  - INSTANCE=lwrp-rule-create-custom-ubuntu-1604
  - INSTANCE=lwrp-rule-create-custom-ubuntu-1804
  - INSTANCE=lwrp-rule-create-custom-ubuntu-1904
  - INSTANCE=lwrp-rule-create-custom-debian-8
  - INSTANCE=lwrp-rule-create-custom-debian-9
  - INSTANCE=lwrp-rule-create-custom-debian-10
  - INSTANCE=lwrp-rule-create-custom-centos-6
  - INSTANCE=lwrp-rule-create-custom-centos-7
  - INSTANCE=lwrp-rule-create-custom-chain-ubuntu-1604
  - INSTANCE=lwrp-rule-create-custom-chain-ubuntu-1804
  - INSTANCE=lwrp-rule-create-custom-chain-ubuntu-1904
  - INSTANCE=lwrp-rule-create-custom-chain-debian-8
  - INSTANCE=lwrp-rule-create-custom-chain-debian-9
  - INSTANCE=lwrp-rule-create-custom-chain-debian-10
  - INSTANCE=lwrp-rule-create-custom-chain-centos-6
  - INSTANCE=lwrp-rule-create-custom-chain-centos-7
  - INSTANCE=lwrp-rule-create-if-missing-ubuntu-1604
  - INSTANCE=lwrp-rule-create-if-missing-ubuntu-1804
  - INSTANCE=lwrp-rule-create-if-missing-ubuntu-1904
  - INSTANCE=lwrp-rule-create-if-missing-debian-8
  - INSTANCE=lwrp-rule-create-if-missing-debian-9
  - INSTANCE=lwrp-rule-create-if-missing-debian-10
  - INSTANCE=lwrp-rule-create-if-missing-centos-6
  - INSTANCE=lwrp-rule-create-if-missing-centos-7
  - INSTANCE=lwrp-rule-delete-ubuntu-1604
  - INSTANCE=lwrp-rule-delete-ubuntu-1804
  - INSTANCE=lwrp-rule-delete-ubuntu-1904
  - INSTANCE=lwrp-rule-delete-debian-8
  - INSTANCE=lwrp-rule-delete-debian-9
  - INSTANCE=lwrp-rule-delete-debian-10
  - INSTANCE=lwrp-rule-delete-centos-6
  - INSTANCE=lwrp-rule-delete-centos-7
  - INSTANCE=lwrp-rule-check-order-ubuntu-1604
  - INSTANCE=lwrp-rule-check-order-ubuntu-1804
  - INSTANCE=lwrp-rule-check-order-ubuntu-1904
  - INSTANCE=lwrp-rule-check-order-debian-8
  - INSTANCE=lwrp-rule-check-order-debian-9
  - INSTANCE=lwrp-rule-check-order-debian-10
  - INSTANCE=lwrp-rule-check-order-centos-6
  - INSTANCE=lwrp-rule-check-order-centos-7
  - INSTANCE=recipe-default-ubuntu-1604
  - INSTANCE=recipe-default-ubuntu-1804
  - INSTANCE=recipe-default-ubuntu-1904
  - INSTANCE=recipe-default-debian-8
  - INSTANCE=recipe-default-debian-9
  - INSTANCE=recipe-default-debian-10
  - INSTANCE=recipe-default-centos-6
  - INSTANCE=recipe-default-centos-7
  - INSTANCE=recipe-install-ubuntu-1604
  - INSTANCE=recipe-install-ubuntu-1804
  - INSTANCE=recipe-install-ubuntu-1904
  - INSTANCE=recipe-install-debian-8
  - INSTANCE=recipe-install-debian-9
  - INSTANCE=recipe-install-debian-10
  - INSTANCE=recipe-install-centos-6
  - INSTANCE=recipe-install-centos-7
  - INSTANCE=attribute-enabled-tables-ubuntu-1604
  - INSTANCE=attribute-enabled-tables-ubuntu-1804
  - INSTANCE=attribute-enabled-tables-ubuntu-1904
  - INSTANCE=attribute-enabled-tables-debian-8
  - INSTANCE=attribute-enabled-tables-debian-9
  - INSTANCE=attribute-enabled-tables-debian-10
  - INSTANCE=attribute-enabled-tables-centos-6
  - INSTANCE=attribute-enabled-tables-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
